### ISSUE TITLE
Join qunitjs organisation

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/node-qunit#134]
Hi @kof,

Would you be interested in having this repository join the @qunitjs organisation? I'd be happy to accept a transfer consider node-qunit a more official part of the QUnit family.

Let me know what you think,
– Timo

/cc @leobalter @jzaefferer 

PS: Note that in case of [transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/), GitHub will maintain full redirects for all urls and git interaction.

**Comment by kof** [comment]
sure!

**Comment by Krinkle** [comment]
@kof Okay. GitHub only allows transfer from an org member. Assuming you'll want to join yourself as well, I've invited you to the org. From there you can transfer the repo.
