### ISSUE TITLE
this being `qunit` on npm but working different in the cli than `qunitjs` is very confusing

### ISSUE THREAD

**Issue by jennschiffer** [qunitjs/node-qunit#136]
i ran `npm install qunit` thinking that was the canonical qunit module, not this "node-qunit" project. this was confusing because the command line required flags for this project vary a lot from `qunitjs` (which require none). it would be cool if the project came up with a better way to distinguish the two projects to lessen confusion about the difference between the two.

thanks for all your work on qunit though, glad it's still around and actively worked on :)

**Comment by jzaefferer** [comment]
From some Gitter discussion, @trentmwillis wrote:

> we should migrate qunitjs on NPM to qunit.
> I think we should likely release one more patch/minor version of qunitjs and log a message stating that users should use the qunit package and begin publishing under that name
> Actually, might need to be a bit more nuanced than that, since the qunit package currently has a decent number of monthly downloads (~30k).
> qunitjs is currently at version 2.4.0 and qunit is at version 1.0.0.
> My thinking is we should release version 2.4.1 which changes nothing but on install logs a message saying that the package is deprecated and uses should switch to the qunit package.
> We will then begin to publish under the qunit package at version 2.5.0 to avoid potential confusion with overlapping version numbers.
> The current qunit package can then be renamed to node-qunit if it is desirable to continue to maintain it.
> If this seems reasonable and someone can add me as an owner to qunit on npm, I'd be willing to take care of this stuff

I finally fixed that now:
```
$ npm owner ls qunitjs
gibson042 <richard.gibson@gmail.com>
jzaefferer <joern.zaefferer@gmail.com>
leobalter <leonardo.balter@gmail.com>
trentmwillis <trentmwillis@gmail.com>
```

**Comment by trentmwillis** [comment]
Thanks! I'll try to take care of deprecations and necessary name changes sometime in the near future.

**Comment by trentmwillis** [comment]
We are now publishing this package as `node-qunit` and QUnit itself will now use the `qunit` package name. The old `qunitjs` package will stay at it's current version moving forward. Hopefully this avoids confusion for future users!

**Comment by jennschiffer** [comment]
thanks! y'all rule
