### ISSUE TITLE
upgrade to qunitjs 2.4.0

### ISSUE THREAD

**Issue by HubertPrzybysz** [qunitjs/node-qunit#138]
Any chance to upgrade to qunitjs 2.4.0 ? 

I use async tests quite a bit and find the assert.timeout introduced in 2.4.0 very useful.

**Comment by AndreyGladkov** [comment]
Any chance to upgrade to qunitjs  2.7.0 ?

**Comment by kof** [comment]
Who wants to be added as  a maintainer to do that?

**Comment by Krinkle** [comment]
Done, as of https://github.com/qunitjs/node-qunit/pull/144.
