### ISSUE TITLE
make output TAP conform

### ISSUE THREAD

**Issue by kof** [qunitjs/node-qunit#17]
http://testanything.org/wiki/index.php/Main_Page

**Comment by Krinkle** [comment]
Note that the official QUnit CLI has a TAP reporter built-in and enabled by default: <https://qunitjs.com/cli/>.

I'll keep this issue open but am not likely to work on it myself. Help is welcome however! For anyone intersted, the [js-reporters](https://github.com/js-reporters/js-reporters) package provides everything you need to create a TAP reporter in Node.js.
